name: Update Mods

on:
  repository_dispatch:
    types: [update-mods]

permissions:
  contents: write  # Allow writing to the repository

jobs:
  update-mods-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get input data
        run: |
          echo "MOD_NAME=${{ github.event.client_payload.mod_name }}" >> $GITHUB_ENV
          echo "MOD_LINK=${{ github.event.client_payload.mod_link }}" >> $GITHUB_ENV

      - name: Append mod to mods.txt
        run: |
          echo "${{ env.MOD_NAME }} | ${{ env.MOD_LINK }}" >> mods.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GIT }}  # Uses your GitHub secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add mods.txt
          git commit -m "Added mod: ${{ env.MOD_NAME }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/TheVrEnthusiast/HoverMangerBacklot.git
