name: Update Mods

on:
  workflow_dispatch:
    inputs:
      mod_name:
        description: 'Mod Name'
        required: true
      mod_link:
        description: 'Mod GitHub Link'
        required: true

jobs:
  update-mods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add mod to mods.txt
        run: echo "${{ github.event.inputs.mod_name }} | ${{ github.event.inputs.mod_link }}" >> mods.txt

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add mods.txt
          git commit -m "Added new mod: ${{ github.event.inputs.mod_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
